# config path: C:\Users\[username]\AppData\Roaming\alacritty

[terminal]
shell = { program = 'C:\Program Files\WSL\wsl.exe', args = ["--cd ~"] }

[font]
size = 12

[font.normal]
family = 'FiraCode Nerd Font Mono'
style = 'Regular'

[font.bold]
family = 'FiraCode Nerd Font Mono'
style = 'SemiBold'

[font.italic]
family = 'FiraCode Nerd Font Mono'
style = 'Italic'

[font.bold_italic]
family = 'FiraCode Nerd Font Mono'
style = 'Bold Italic'


[general]
import = [
    "catppuccin-mocha.toml"
]
